### ISSUE TITLE
Prevent spam from being sent through our event request form

### ISSUE THREAD

**Issue by bridget-tan** [ABTech/abtech.org#106]
A group has been occasionally sending spam through the event request form.

**Comment by DaAwesomeP** [comment]
Quickest solution @timparenti has recommended is just adding shib login to that page. Would that work? I could probably do that this week.

**Comment by timparenti** [comment]
Sticking `/request` behind a Shibboleth login would be a quick solution to the spam problem, but @tedgarb pointed out there may be issues with that given how the site is currently proxied.

This problem does resurface the need to address https://github.com/ABTech/tracker/issues/405, which would bring the form into Tracker (which can also be authenticated) and eliminate the need for the current complexity on the website.

**Comment by DaAwesomeP** [comment]
Yes, long-term it should be submitted directly to tracker, but for the moment we could add this page to shib in Apache.

**Comment by DaAwesomeP** [comment]
This will be fixed on the tracker end. Current plan is to reject events that have invalid dates (i.e. 1973 keeps showing up).
