### ISSUE TITLE
Equipment Page Edits

### ISSUE THREAD

**Issue by izhanchang** [ABTech/abtech.org#136]
1. Revise Dimming:
•	Up to 12 channels of dimming at 1800W/pack, 3 channels per pack (Leprecon ULD-360-HP)
2. Add Media Switchers: 1 Blackmagic Design ATEM 1 M/E Constellation HD Live Production Switcher (1 RU)
1 Blackmagic Design ATEM Mini HDMI Live Stream Switcher
3. Miscellaneous: update truss numbers (7 10' truss) and add 3 3-phase Power Distributors with varying cable configurations
5. Sound: Add old mackies?

**Comment by DaAwesomeP** [comment]
> Up to 12 channels of dimming at 1800W/pack, 3 channels per pack (Leprecon ULD-360-HP)

The current wording doesn't make sense but this doesn't make sense to be either. The limitations are:
 - 6 channels per pack
 - Split into two groups of 3
 - Each group of 3 is limited to 1800W
 - We have 2 packs (I think)
 
 > 3 3-phase Power Distributors
 I would call this 208Y/120 Power Distribution System. We definitely have more than "3" but our terminology of a PD doesn't necessary match common usage and definitely doesn't include breakouts/stringers/etc.
