### ISSUE TITLE
Mobile logo sad

### ISSUE THREAD

**Issue by rmaratos** [ABTech/abtech.org#26]
![img_5717](https://cloud.githubusercontent.com/assets/5491270/17355600/811177cc-5906-11e6-838c-87cde0b269c7.PNG)

**Comment by kicohen** [comment]
How did you create this error, I haven't been able to replicate it?

**Comment by rmaratos** [comment]
huh....maybe iOS 10...it's fine on christine's phone.

but it's bad in mobile chrome and safari for me.

**Comment by rmaratos** [comment]
I'll close this for now...hopefully iOS 10 updates fix it, if not will revisit in september.
