### ISSUE TITLE
Contractors Navigation Inconsistent

### ISSUE THREAD

**Issue by rmaratos** [ABTech/abtech.org#30]
Having to go two levels deep to get contractors is annoying, fwiw.

**Comment by rmaratos** [comment]
oh yeah /contractors doesn't need to be nested like that

**Comment by kicohen** [comment]
I just don't think that's a problem, if you would like it changed, I can but honestly if you are looking for external contractors on our website, you should be able to find it.

**Comment by rmaratos** [comment]
For "services/equipment" tab, maybe have the 3 options as a drop down that appears upon mouse-over (design choice)

**Comment by rmaratos** [comment]
This was two issues so I split it up, with the hover stuff being an enhancement for the fall.

I think the navigation to contractors is inconsistent with everything else. They should just show up on /external Also there's plenty of ones we don't use any more so the list can be made smaller.
