### ISSUE TITLE
Front Page Image Quality

### ISSUE THREAD

**Issue by rmaratos** [ABTech/abtech.org#32]
why are the images on the front page jpg-y

**Comment by kicohen** [comment]
Would you prefer RAW?

**Comment by rmaratos** [comment]
I don't know. I'd check out other websites that do the full background
image thing to see what the best format/resolution is. There's probably
articles on that too. We want a balance of quality vs file size so the load
time isn't too bad

**Comment by kicohen** [comment]
Fixed in latest pull request.
