### ISSUE TITLE
Map wants you to climb grate

### ISSUE THREAD

**Issue by plima101** [ABTech/abtech.org#50]
Hi fam,

So the map on: https://www.abtech.org/static/img/abtech_room.png wants people to climb through the grate by Rangos instead of using the U ramp. The red path should have members going though the ramp.

Best,
Pedro

**Comment by tedgarb** [comment]
The red line also requires people to fly over the staircase instead of walking next to it

**Comment by timparenti** [comment]
The blue line also appears to go along the corridor next to Rangos, and not the ramp.

**Comment by christinelxu** [comment]
dang didn't save psd will change

**Comment by christinelxu** [comment]
lol whoops lucky i still have psd
